use fancy_regex::Regex;
use std::cmp::{Ordering, Reverse};
use std::collections::{BinaryHeap, HashMap};
use std::sync::OnceLock;

// Generated by build.rs from ai-tokenizer Claude encoding; vendored in-tree so
// the crate builds from a clean clone without fetching `tmp/ai-tokenizer-pkg/`.
// To refresh: see crates/aft-tokenizer/build.rs.
include!("claude_data.rs");

const PAT_STR: &str = r"'s|'t|'re|'ve|'m|'ll|'d| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+";
const NO_RANK: u32 = u32::MAX;

static PATTERN_REGEX: OnceLock<Regex> = OnceLock::new();
static STRING_ENCODER: OnceLock<HashMap<&'static str, u32>> = OnceLock::new();
static BINARY_ENCODER: OnceLock<HashMap<Vec<u8>, u32>> = OnceLock::new();

/// Count Claude tokens in `text`.
pub fn count_tokens(text: &str) -> usize {
    if text.is_empty() {
        return 0;
    }
    encode_internal(text).len()
}

/// Encode `text` into Claude token IDs.
pub fn encode(text: &str) -> Vec<u32> {
    if text.is_empty() {
        return Vec::new();
    }
    encode_internal(text)
}

fn encode_internal(text: &str) -> Vec<u32> {
    // ai-tokenizer checks direct rank before pre-tokenizing for short strings.
    if text.encode_utf16().take(10).count() < 10 {
        if let Some(&rank) = string_encoder().get(text) {
            return vec![rank];
        }
    }

    let mut result = Vec::new();
    for piece in pattern_regex().find_iter(text) {
        let piece = piece
            .expect("Claude pre-tokenizer regex should not fail")
            .as_str();

        if let Some(&rank) = string_encoder().get(piece) {
            result.push(rank);
            continue;
        }

        result.extend(byte_pair_merge(piece.as_bytes()));
    }
    result
}

fn pattern_regex() -> &'static Regex {
    PATTERN_REGEX.get_or_init(|| Regex::new(PAT_STR).expect("Claude pre-tokenizer regex"))
}

fn string_encoder() -> &'static HashMap<&'static str, u32> {
    STRING_ENCODER.get_or_init(|| STRING_ENCODER_ENTRIES.iter().copied().collect())
}

fn binary_encoder() -> &'static HashMap<Vec<u8>, u32> {
    BINARY_ENCODER.get_or_init(|| {
        BINARY_ENCODER_ENTRIES
            .iter()
            .map(|(bytes, rank)| (bytes.to_vec(), *rank))
            .collect()
    })
}

fn byte_pair_merge(piece: &[u8]) -> Vec<u32> {
    #[cfg(test)]
    if LEGACY_BPE.with(|legacy| legacy.get()) {
        return byte_pair_merge_legacy(piece);
    }
    let len = piece.len();
    // Byte offsets are stable node IDs. Removing a boundary only relinks its
    // neighbours; it never shifts the remaining offsets or pending candidates.
    let mut next: Vec<usize> = (1..=len + 1).collect();
    let mut previous: Vec<usize> = (0..=len).map(|i| i.saturating_sub(1)).collect();
    let mut heap = BinaryHeap::new();
    for left in 0..len.saturating_sub(1) {
        enqueue_pair(piece, &next, left, &mut heap);
    }
    while let Some(Reverse(candidate)) = heap.pop() {
        let MergeCandidate(_, left, right, end) = candidate;
        // A neighbouring merge invalidates the old pair, including its rank.
        if next[left] != right || next[right] != end {
            continue;
        }
        next[left] = end;
        next[right] = usize::MAX;
        previous[end] = left;
        enqueue_pair(piece, &next, left, &mut heap);
        if left > 0 {
            enqueue_pair(piece, &next, previous[left], &mut heap);
        }
    }
    let mut output = Vec::new();
    let mut left = 0;
    while left < len {
        let right = next[left];
        let rank = get_rank_for_slice(&piece[left..right]);
        if rank != NO_RANK {
            output.push(rank);
        }
        left = right;
    }
    output
}

// Ordering by the original left offset preserves the legacy scan's leftmost
// tie-break, even after earlier boundaries have been removed.
#[derive(Eq, PartialEq)]
struct MergeCandidate(u32, usize, usize, usize);

impl Ord for MergeCandidate {
    fn cmp(&self, other: &Self) -> Ordering {
        #[cfg(test)]
        BPE_WORK.with(|work| work.set(work.get() + 1));
        (self.0, self.1, self.2, self.3).cmp(&(other.0, other.1, other.2, other.3))
    }
}

impl PartialOrd for MergeCandidate {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

fn enqueue_pair(
    piece: &[u8],
    next: &[usize],
    left: usize,
    heap: &mut BinaryHeap<Reverse<MergeCandidate>>,
) {
    let right = next[left];
    if right >= piece.len() {
        return;
    }
    let end = next[right];
    let rank = get_rank_for_slice(&piece[left..end]);
    if rank != NO_RANK {
        heap.push(Reverse(MergeCandidate(rank, left, right, end)));
    }
}

#[cfg(test)]
thread_local! {
    static BPE_WORK: std::cell::Cell<usize> = const { std::cell::Cell::new(0) };
    static LEGACY_BPE: std::cell::Cell<bool> = const { std::cell::Cell::new(false) };
}

#[cfg(test)]
fn byte_pair_merge_legacy(piece: &[u8]) -> Vec<u32> {
    let len = piece.len();
    let mut starts = Vec::with_capacity(len + 1);
    let mut ranks = Vec::with_capacity(len + 1);

    for i in 0..=len {
        starts.push(i);
        if i < len.saturating_sub(1) {
            ranks.push(get_rank_for_slice(&piece[i..i + 2]));
        } else {
            ranks.push(NO_RANK);
        }
    }

    while starts.len() > 1 {
        let mut min_rank = NO_RANK;
        let mut min_idx = None;
        for (idx, &rank) in ranks.iter().take(ranks.len().saturating_sub(1)).enumerate() {
            BPE_WORK.with(|work| work.set(work.get() + 1));
            if rank < min_rank {
                min_rank = rank;
                min_idx = Some(idx);
            }
        }

        let Some(min_idx) = min_idx else { break };
        if min_rank == NO_RANK {
            break;
        }

        BPE_WORK.with(|work| {
            work.set(work.get() + starts.len() - min_idx - 2 + ranks.len() - min_idx - 1)
        });
        starts.remove(min_idx + 1);
        ranks.remove(min_idx);
        if min_idx < ranks.len() {
            ranks[min_idx] = get_rank(piece, &starts, min_idx);
        }
        if min_idx > 0 {
            ranks[min_idx - 1] = get_rank(piece, &starts, min_idx - 1);
        }
    }

    let mut output = Vec::with_capacity(starts.len().saturating_sub(1));
    for window in starts.windows(2) {
        let rank = get_rank_for_slice(&piece[window[0]..window[1]]);
        if rank != NO_RANK {
            output.push(rank);
        }
    }
    output
}

#[cfg(test)]
fn get_rank(piece: &[u8], starts: &[usize], start_index: usize) -> u32 {
    let Some(&pair_start) = starts.get(start_index) else {
        return NO_RANK;
    };
    let Some(&pair_end) = starts.get(start_index + 2) else {
        return NO_RANK;
    };
    get_rank_for_slice(&piece[pair_start..pair_end])
}

fn get_rank_for_slice(slice: &[u8]) -> u32 {
    if let Ok(as_string) = std::str::from_utf8(slice) {
        if let Some(&rank) = string_encoder().get(as_string) {
            return rank;
        }
    }

    binary_encoder().get(slice).copied().unwrap_or(NO_RANK)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_input_has_no_tokens() {
        assert!(encode("").is_empty());
        assert_eq!(count_tokens(""), 0);
    }

    #[test]
    fn direct_ascii_token() {
        assert_eq!(encode("!"), vec![5]);
        assert_eq!(count_tokens("!"), 1);
    }

    #[test]
    fn bpe_heap_work_is_bounded_and_tokens_are_identical() {
        let mut corpus = vec![
            "=".repeat(8192),
            "\n".repeat(8192),
            " \n\t".repeat(2048),
            "Hello, world! café 中文 🦀\nexport const foo = (x: number) => x + 1;\n".repeat(20),
        ];
        // Exercise tied ranks, binary byte tokens and changes on both sides of
        // a merge without deriving expectations from the new implementation.
        for n in 0..128 {
            corpus.push(
                (0..n)
                    .map(|i| ['=', 'a', '\n', 'é', '🦀', ' '][(i * 17 + n) % 6])
                    .collect(),
            );
        }
        for (index, text) in corpus.iter().enumerate() {
            LEGACY_BPE.with(|legacy| legacy.set(true));
            BPE_WORK.with(|work| work.set(0));
            let reference = encode(text);
            let before = BPE_WORK.with(|work| work.get());
            LEGACY_BPE.with(|legacy| legacy.set(false));
            BPE_WORK.with(|work| work.set(0));
            let actual = encode(text);
            let after = BPE_WORK.with(|work| work.get());
            assert_eq!(actual, reference, "corpus item {index}");
            assert_eq!(count_tokens(text), reference.len());
            if index < 4 {
                eprintln!(
                    "BPE corpus {index}: comparisons + shifts {before} -> {after}, {} tokens",
                    actual.len()
                );
            }
            assert!(
                after <= 64 * text.len(),
                "{after} operations for {} bytes",
                text.len()
            );
        }
        for text in ["=".repeat(128 * 1024), "\n".repeat(128 * 1024)] {
            assert!(!encode(&text).is_empty());
        }
    }
}
